### ISSUE TITLE
Can't Clean & Build the project - Copy

### ISSUE THREAD

**Issue by spdvi** [AlejoPinto01/OpusList#1]
If I clone the project and I open it in NetBeans it says that the gson library was not found.
![image](https://user-images.githubusercontent.com/62358226/140432040-46f90504-d7e4-450f-a0ad-aceb05f362c5.png)
I solve the problem by adding the library to the project but when I run it nothing appears in the JList.
If I try to "Clean & Build" the project an error is shown up:
![image](https://user-images.githubusercontent.com/62358226/140432282-3cff3f2b-82b6-456d-a67b-254c734d8f81.png)
I've been trying several things but I still can't solve the issue.
Any help?

**Comment by AlejoPinto01** [comment]
When I tried the same error showed. I don't have any solution at the
moment, I always run the project from the IDE.
[image: image.png]

And about the library, when executing git push from the project folder it
doesn't upload it to github. I don't know why the problem keeps happening.

**Comment by spdvi** [comment]
Moved the project to maven. Build dependencies should now not be a problem. Just test and let us know if everything works as expected.
